"""Initial Migration

Revision ID: 05b6db1ca1f3
Revises: 
Create Date: 2025-09-24 01:42:26.195369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b6db1ca1f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_due', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('URGENT', 'IMPORTANT', 'NORMAL', 'OPTIONAL', name='prioritytype'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['testing.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('todo_user_id_fkey', 'todos', ['user_id'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('todo_user_id_fkey', table_name='todos', postgresql_using='hash')
    op.drop_table('todos')
    op.drop_table('users')
    # ### end Alembic commands ###
